version: "3"
services: 
  wordpress:
    image: wordpress:latest
    ports:
      - 8000:8080 
    environment:
      WORDPRESS_DB_HOST: mysql_db
      WORDPRESS_DB_PASSWORD: muthur@
  postgres:
    image: postgres:latest
    ports: 
     - 3307:3306   
    environment:
     POSTGRES_PASSWORD: samplepassword
      
